config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "/up", to: "health#show"

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest"       => "rails/pwa#manifest",       as: :pwa_manifest

  post "stripe/webhook" => "stripe/webhooks#receive"

  scope "(:locale)", locale: /en|ru|es/ do
    devise_for :users

    get "analytics", to: "analytics#dashboard", as: :analytics_dashboard
    get  "billing"          => "billing#pricing"
    post "billing/subscribe"=> "billing#subscribe"
    post "billing/portal"   => "billing#portal"
    get  "billing/success"  => "billing#success"
    get  "billing/cancel"   => "billing#cancel"

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => "/sidekiq", as: :sidekiq_web
    end

    resources :clients
    resources :invoices do
      member do
        post :send_created
        post :send_due
        post :send_overdue
        post :send_paid
        get  :pay
      end
    end

    root "home#index"
  end
end

app/views/layouts/application.html.erb
<!-- BEGIN app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>InvoiceLab</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>

    <!-- Favicon, чтобы убрать лишний 404 -->
    <link rel="icon" href="/icon.png" />

    <%# Vite client + JS. Стили подключаем из JS (см. entrypoints/application.js) %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to t('app.name', default: 'InvoiceLab'), root_path(locale: I18n.locale), class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="nav" class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><%= link_to t('nav.home'), root_path(locale: I18n.locale), class: "nav-link" %></li>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to t('nav.clients'), clients_path(locale: I18n.locale), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to t('nav.invoices'), invoices_path(locale: I18n.locale), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to t('nav.billing', default: 'Billing'), billing_path(locale: I18n.locale), class: "nav-link" %></li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"><%= t('nav.language') %></a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><%= link_to "EN", url_for(locale: :en), class: "dropdown-item" %></li>
                <li><%= link_to "RU", url_for(locale: :ru), class: "dropdown-item" %></li>
                <li><%= link_to "ES", url_for(locale: :es), class: "dropdown-item" %></li>
              </ul>
            </li>
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to_blank t('nav.admin'),
                                    sidekiq_web_path(locale: I18n.locale),
                                    class: "nav-link" %>
                </li>
              <% end %>
              <li class="nav-item"><%= link_to t('nav.sign_out'), destroy_user_session_path(locale: I18n.locale), data: { turbo_method: :delete }, class: "nav-link" %></li>
            <% else %>
              <li class="nav-item"><%= link_to t('nav.sign_in'), new_user_session_path(locale: I18n.locale), class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container py-4">
      <%= render "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>
<!-- END app/views/layouts/application.html.erb -->